### ISSUE TITLE
AWS credentials lost when starting a cluster from stopped state

### ISSUE THREAD

**Issue by npyoung** [thunder-project/thunder#128] opened 2015-03-08 05:03 UTC
Initial login after `thunder-ec2 launch` is fine, but after stopping and starting, I get this error whenever accessing a resource on S3:
```python
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-2-c4e9f34a2087> in <module>()
----> 1 tseries = tsc.loadSeries(series_path)

/mnt/spark/spark-5fd29201-6834-4f40-9a8d-3ad01253881b/spark-c1b91f8e-af1c-4978-8043-3b3c7b160518/thunder_python-0.5.0_dev-py2.6.egg/thunder/utils/context.pyc in loadSeries(self, dataPath, nkeys, nvalues, inputFormat, minPartitions, confFilename, keyType, valueType)
     92             # must be either 'text' or 'binary'
     93             data = loader.fromBinary(dataPath, confFilename=confFilename, nkeys=nkeys, nvalues=nvalues,
---> 94                                      keyType=keyType, valueType=valueType)
     95         return data
     96 

/mnt/spark/spark-5fd29201-6834-4f40-9a8d-3ad01253881b/spark-c1b91f8e-af1c-4978-8043-3b3c7b160518/thunder_python-0.5.0_dev-py2.6.egg/thunder/rdds/fileio/seriesloader.pyc in fromBinary(self, dataPath, ext, confFilename, nkeys, nvalues, keyType, valueType, newDtype, casting)
    210                                          'org.apache.hadoop.io.LongWritable',
    211                                          'org.apache.hadoop.io.BytesWritable',
--> 212                                          conf={'recordLength': str(recordSize)})
    213 
    214         data = lines.map(lambda (_, v):

/root/spark/python/pyspark/context.pyc in newAPIHadoopFile(self, path, inputFormatClass, keyClass, valueClass, keyConverter, valueConverter, conf, batchSize)
    510         jrdd = self._jvm.PythonRDD.newAPIHadoopFile(self._jsc, path, inputFormatClass, keyClass,
    511                                                     valueClass, keyConverter, valueConverter,
--> 512                                                     jconf, batchSize)
    513         return RDD(jrdd, self)
    514 

/root/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    536         answer = self.gateway_client.send_command(command)
    537         return_value = get_return_value(answer, self.gateway_client,
--> 538                 self.target_id, self.name)
    539 
    540         for temp_arg in temp_args:

/root/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    298                 raise Py4JJavaError(
    299                     'An error occurred while calling {0}{1}{2}.\n'.
--> 300                     format(target_id, '.', name), value)
    301             else:
    302                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.newAPIHadoopFile.
: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3n URL, or by setting the fs.s3n.awsAccessKeyId or fs.s3n.awsSecretAccessKey properties (respectively).
```
This is fixed by manually setting AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in the current terminal session. The expected behavior is for the AWS access information to persist on the remote, or to be resent with `thunder-ec2 start`

**Comment by freeman-lab** [comment] 2015-03-08 09:46
Thanks for catching this @npyoung , turns out a few other settings were getting lost during the `start`-`stop` cycle as well. I identified which settings needed resetting, and just pushed a minor refactor that splits off the Thunder install (which is preserved during a restart) from a set of Spark configuration steps (which includes setting the AWS credentials), and reruns the latter during a restart.

Confirmed with the fix that this call:

```
data, params = tsc.loadExampleS3('svoboda.lab/tactile.navigation')
```

which requires AWS credentials, works after `launch` (as it did before), and also after a `stop`-`start`.

**Comment by freeman-lab** [comment] 2015-03-08 09:57
Fixed by https://github.com/thunder-project/thunder/commit/d4fe23fff120686a0fab8da5aae5da4ab1409f3c

**Closed** 2015-03-08 09:58 UTC

**Comment by npyoung** [comment] 2015-03-08 21:45
Confirming that the fix works - thanks!

**Comment by freeman-lab** [comment] 2015-03-09 00:51
Great, thanks for checking!
